-- MariaDB schema for MasePOS
-- Use MariaDB 10.2+ for JSON support

CREATE TABLE IF NOT EXISTS tenants (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS slugs (
  slug VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  uid VARCHAR(128) PRIMARY KEY,
  tenant_id VARCHAR(64),
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS refresh_token_sessions (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  staff_id VARCHAR(64) NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  ip_address VARCHAR(128),
  user_agent TEXT,
  expires_at DATETIME,
  revoked_at DATETIME,
  revoked_reason VARCHAR(255),
  replaced_by_token_hash CHAR(64),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  last_used_at DATETIME,
  INDEX idx_refresh_token_sessions_staff (tenant_id, staff_id, revoked_at),
  INDEX idx_refresh_token_sessions_token_hash (token_hash),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS app_settings (
  tenant_id VARCHAR(64) PRIMARY KEY,
  payfast_merchant_id VARCHAR(128) DEFAULT '10000100',
  payfast_merchant_key VARCHAR(128) DEFAULT '46f0cd694581a',
  payfast_passphrase VARCHAR(128) DEFAULT 'jt7v60h69n8a1',
  payfast_sandbox BOOLEAN DEFAULT TRUE,
  business JSON DEFAULT JSON_OBJECT(),
  setup_completed BOOLEAN DEFAULT FALSE,
  categories JSON DEFAULT JSON_OBJECT(),
  retention_policy JSON DEFAULT JSON_OBJECT(),
  slug VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS licences (
  licence_id VARCHAR(64) PRIMARY KEY,
  tenant_name VARCHAR(255) NOT NULL,
  key_hash VARCHAR(128) NOT NULL UNIQUE,
  tier VARCHAR(32) NOT NULL,
  max_registers INT NOT NULL DEFAULT 2,
  features TEXT NOT NULL DEFAULT '[]',
  issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  revoked_at DATETIME,
  revoked_reason TEXT,
  INDEX idx_licences_key_hash (key_hash)
);

CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  cost_price DECIMAL(12,2) DEFAULT 0,
  section VARCHAR(255),
  category VARCHAR(255),
  sub_category VARCHAR(255),
  stock INT DEFAULT 0,
  min_stock INT DEFAULT 0,
  image_url TEXT,
  barcode VARCHAR(255),
  workstation_id VARCHAR(64),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS inventory_locations (
  id VARCHAR(64) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  type ENUM('branch','warehouse','register','kitchen','other') NOT NULL DEFAULT 'branch',
  status ENUM('active','inactive') NOT NULL DEFAULT 'active',
  is_default BOOLEAN DEFAULT FALSE,
  address TEXT,
  notes TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (tenant_id, id),
  INDEX idx_inventory_locations_status (tenant_id, status),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product_location_stock (
  tenant_id VARCHAR(64) NOT NULL,
  product_id VARCHAR(64) NOT NULL,
  location_id VARCHAR(64) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL DEFAULT 0,
  min_stock DECIMAL(12,3) NOT NULL DEFAULT 0,
  reorder_threshold DECIMAL(12,3) NOT NULL DEFAULT 0,
  updated_by VARCHAR(64),
  updated_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (tenant_id, product_id, location_id),
  INDEX idx_product_location_stock_location (tenant_id, location_id),
  INDEX idx_product_location_stock_reorder (tenant_id, location_id, reorder_threshold),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS customers (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(64),
  address TEXT,
  notes TEXT,
  loyalty_points INT DEFAULT 0,
  loyalty_member_status ENUM('active','paused','opted_out') DEFAULT 'active',
  loyalty_tier_id VARCHAR(64),
  membership_card_id VARCHAR(128),
  membership_barcode VARCHAR(128),
  membership_started_at DATETIME,
  wallet_balance DECIMAL(12,2) DEFAULT 0,
  account_enabled TINYINT(1) DEFAULT 0,
  account_limit DECIMAL(12,2) DEFAULT 0,
  account_balance DECIMAL(12,2) DEFAULT 0,
  discount_percent DECIMAL(5,2) DEFAULT 0,
  uid VARCHAR(128),
  is_anonymized TINYINT(1) DEFAULT 0,
  anonymized_at DATETIME,
  anonymized_by VARCHAR(64),
  anonymized_by_name VARCHAR(255),
  anonymization_reason TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS customer_consents (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  customer_id VARCHAR(64) NOT NULL,
  consent_type ENUM('loyalty','marketing','customer_portal','stored_contact_details','promotions','ai_recommendations') NOT NULL,
  status ENUM('unknown','granted','denied','revoked') NOT NULL DEFAULT 'unknown',
  source VARCHAR(80),
  note TEXT,
  captured_by VARCHAR(64),
  captured_by_name VARCHAR(255),
  captured_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_customer_consents_type (tenant_id, customer_id, consent_type),
  INDEX idx_customer_consents_customer (tenant_id, customer_id),
  INDEX idx_customer_consents_status (tenant_id, consent_type, status),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS customer_consent_events (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  customer_id VARCHAR(64) NOT NULL,
  consent_type ENUM('loyalty','marketing','customer_portal','stored_contact_details','promotions','ai_recommendations') NOT NULL,
  previous_status ENUM('unknown','granted','denied','revoked') DEFAULT 'unknown',
  status ENUM('unknown','granted','denied','revoked') NOT NULL,
  source VARCHAR(80),
  note TEXT,
  captured_by VARCHAR(64),
  captured_by_name VARCHAR(255),
  captured_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_customer_consent_events_customer (tenant_id, customer_id, created_at),
  INDEX idx_customer_consent_events_type (tenant_id, consent_type, created_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS loyalty_tiers (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(160) NOT NULL,
  status ENUM('active','inactive') DEFAULT 'active',
  min_points INT DEFAULT 0,
  earn_multiplier DECIMAL(8,3) DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_loyalty_tiers_threshold (tenant_id, status, min_points),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS loyalty_reward_rules (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(160) NOT NULL,
  status ENUM('active','inactive') DEFAULT 'active',
  rule_type ENUM('base','category','product','time_window') DEFAULT 'base',
  points_per_currency DECIMAL(12,4) DEFAULT 0,
  multiplier DECIMAL(8,3) DEFAULT 1,
  bonus_points INT DEFAULT 0,
  min_subtotal DECIMAL(12,2) DEFAULT 0,
  starts_at DATETIME,
  ends_at DATETIME,
  target_product_ids JSON DEFAULT JSON_ARRAY(),
  target_categories JSON DEFAULT JSON_ARRAY(),
  days_of_week JSON DEFAULT JSON_ARRAY(),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_loyalty_reward_rules_status (tenant_id, status, rule_type),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS staff (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role ENUM('admin','cashier','manager','chef','dev') DEFAULT 'cashier',
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255),
  security_pin_hash VARCHAR(255),
  two_factor_enabled TINYINT(1) DEFAULT 0,
  two_factor_secret VARCHAR(255),
  two_factor_confirmed_at DATETIME,
  phone VARCHAR(64),
  status ENUM('active','inactive') DEFAULT 'active',
  permissions JSON DEFAULT JSON_OBJECT(),
  assigned_sections JSON DEFAULT JSON_ARRAY(),
  assigned_categories JSON DEFAULT JSON_ARRAY(),
  id_number VARCHAR(128),
  pay_rate DECIMAL(12,2) DEFAULT 0,
  pay_type ENUM('hourly','salary'),
  accumulated_leave INT DEFAULT 0,
  wallet_balance DECIMAL(12,2) DEFAULT 0,
  discount_percent DECIMAL(5,2) DEFAULT 0,
  default_location_id VARCHAR(64),
  assigned_location_ids JSON DEFAULT JSON_ARRAY(),
  metrics JSON DEFAULT JSON_OBJECT(),
  badges JSON DEFAULT JSON_ARRAY(),
  rank VARCHAR(128),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS staff_shifts (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  staff_id VARCHAR(64) NOT NULL,
  staff_name VARCHAR(255) NOT NULL,
  role VARCHAR(32),
  shift_date DATE NOT NULL,
  start_at DATETIME NOT NULL,
  end_at DATETIME NOT NULL,
  status ENUM('draft','published','cancelled','completed') DEFAULT 'draft',
  location_id VARCHAR(64),
  break_minutes_planned INT DEFAULT 0,
  notes TEXT,
  published_at DATETIME,
  published_by VARCHAR(64),
  published_by_name VARCHAR(255),
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_staff_shifts_roster (tenant_id, shift_date, status),
  KEY idx_staff_shifts_staff (tenant_id, staff_id, shift_date),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS staff_attendance (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  staff_id VARCHAR(64) NOT NULL,
  staff_name VARCHAR(255) NOT NULL,
  shift_id VARCHAR(64),
  status ENUM('open','closed') DEFAULT 'open',
  clock_in_at DATETIME NOT NULL,
  clock_out_at DATETIME,
  break_started_at DATETIME,
  break_minutes INT DEFAULT 0,
  scheduled_minutes INT DEFAULT 0,
  worked_minutes INT DEFAULT 0,
  regular_minutes INT DEFAULT 0,
  overtime_minutes INT DEFAULT 0,
  pay_rate DECIMAL(12,2) DEFAULT 0,
  pay_type ENUM('hourly','salary') DEFAULT 'hourly',
  payroll_amount DECIMAL(12,2) DEFAULT 0,
  note TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_staff_attendance_staff (tenant_id, staff_id, clock_in_at),
  KEY idx_staff_attendance_status (tenant_id, status),
  KEY idx_staff_attendance_shift (tenant_id, shift_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE,
  FOREIGN KEY (shift_id) REFERENCES staff_shifts(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tip_pool_rules (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  status ENUM('active','inactive') DEFAULT 'active',
  distribution_method ENUM('worked_hours','equal_shift','role_weighted') DEFAULT 'worked_hours',
  source ENUM('sale_tips') DEFAULT 'sale_tips',
  included_roles JSON DEFAULT JSON_ARRAY(),
  role_weights JSON DEFAULT JSON_OBJECT(),
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_tip_pool_rules_status (tenant_id, status),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tip_pool_payouts (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  rule_id VARCHAR(64) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  staff_id VARCHAR(64) NOT NULL,
  staff_name VARCHAR(255) NOT NULL,
  attendance_id VARCHAR(64),
  shift_id VARCHAR(64),
  shift_date DATE,
  worked_minutes INT DEFAULT 0,
  weight DECIMAL(12,4) DEFAULT 0,
  tip_pool_amount DECIMAL(12,2) DEFAULT 0,
  payout_amount DECIMAL(12,2) DEFAULT 0,
  status ENUM('draft','approved','paid','void') DEFAULT 'draft',
  generated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  generated_by VARCHAR(64),
  generated_by_name VARCHAR(255),
  approved_at DATETIME,
  approved_by VARCHAR(64),
  approved_by_name VARCHAR(255),
  paid_at DATETIME,
  paid_by VARCHAR(64),
  paid_by_name VARCHAR(255),
  notes TEXT,
  KEY idx_tip_pool_payouts_period (tenant_id, period_start, period_end, status),
  KEY idx_tip_pool_payouts_staff (tenant_id, staff_id, shift_date),
  KEY idx_tip_pool_payouts_rule (tenant_id, rule_id, period_start, period_end),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (rule_id) REFERENCES tip_pool_rules(id) ON DELETE CASCADE,
  FOREIGN KEY (attendance_id) REFERENCES staff_attendance(id) ON DELETE SET NULL,
  FOREIGN KEY (shift_id) REFERENCES staff_shifts(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS staff_coaching_notes (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  staff_id VARCHAR(64) NOT NULL,
  staff_name VARCHAR(255) NOT NULL,
  note_type ENUM('coaching','recognition','warning','follow_up') DEFAULT 'coaching',
  title VARCHAR(255) NOT NULL,
  note TEXT NOT NULL,
  source ENUM('manager','ai','performance') DEFAULT 'manager',
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY idx_staff_coaching_notes_staff (tenant_id, staff_id, created_at),
  KEY idx_staff_coaching_notes_type (tenant_id, note_type, created_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS workstations (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  type ENUM('kitchen','bar','other') DEFAULT 'other',
  status ENUM('active','inactive') DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS companion_device_assignments (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  device_id VARCHAR(128) NOT NULL,
  device_name VARCHAR(255) NOT NULL,
  workstation_id VARCHAR(64) NOT NULL,
  default_mode ENUM('remote_control','wireless_scanner','pole_display') DEFAULT 'remote_control',
  assigned_by VARCHAR(64),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_companion_device (tenant_id, device_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (workstation_id) REFERENCES workstations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hardware_devices (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(160) NOT NULL,
  device_type ENUM('receipt_printer','kitchen_printer','cash_drawer','scale','barcode_scanner','pole_display','card_terminal') NOT NULL,
  connection_type ENUM('browser_print','escpos_network','escpos_usb','serial','webserial','webhid','keyboard_wedge','local_bridge','payment_provider') NOT NULL,
  status ENUM('active','inactive') NOT NULL DEFAULT 'active',
  workstation_id VARCHAR(64),
  is_default BOOLEAN DEFAULT FALSE,
  connection_config JSON DEFAULT JSON_OBJECT(),
  capabilities JSON DEFAULT JSON_ARRAY(),
  last_check_status VARCHAR(32),
  last_check_message TEXT,
  last_checked_at DATETIME,
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_hardware_devices_tenant_type (tenant_id, device_type, status),
  INDEX idx_hardware_devices_workstation (tenant_id, workstation_id, device_type),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (workstation_id) REFERENCES workstations(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS hardware_device_events (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  device_id VARCHAR(64),
  event_type VARCHAR(64) NOT NULL,
  command_type VARCHAR(64) NOT NULL,
  status ENUM('queued','sent','failed','skipped') NOT NULL DEFAULT 'queued',
  request_payload JSON DEFAULT JSON_OBJECT(),
  response_payload JSON DEFAULT JSON_OBJECT(),
  error_message TEXT,
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_hardware_device_events_tenant (tenant_id, created_at),
  INDEX idx_hardware_device_events_device (tenant_id, device_id, created_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (device_id) REFERENCES hardware_devices(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS sales (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  customer_id VARCHAR(64),
  user_id VARCHAR(128),
  staff_id VARCHAR(64),
  total DECIMAL(12,2) DEFAULT 0,
  subtotal DECIMAL(12,2) DEFAULT 0,
  tax_amount DECIMAL(12,2) DEFAULT 0,
  tax_rate DECIMAL(5,2) DEFAULT 0,
  tax_inclusive BOOLEAN DEFAULT FALSE,
  payment_method ENUM('cash','payfast','card','wallet','account','qr','bnpl','pending') DEFAULT 'pending',
  tendered_amount DECIMAL(12,2) DEFAULT 0,
  change_amount DECIMAL(12,2) DEFAULT 0,
  tip_amount DECIMAL(12,2) DEFAULT 0,
  cash_out_amount DECIMAL(12,2) DEFAULT 0,
  points_discount DECIMAL(12,2) DEFAULT 0,
  promotion_id VARCHAR(64),
  promotion_code VARCHAR(64),
  promotion_discount DECIMAL(12,2) DEFAULT 0,
  status ENUM('pending','completed','failed','open','kitchen') DEFAULT 'pending',
  transaction_type VARCHAR(24) DEFAULT 'sale',
  parent_sale_id VARCHAR(64),
  refund_status VARCHAR(24) DEFAULT 'none',
  refunded_amount DECIMAL(12,2) DEFAULT 0,
  refund_reason TEXT,
  refunded_by VARCHAR(64),
  void_reason TEXT,
  voided_by VARCHAR(64),
  payfast_payment_id VARCHAR(128),
  table_number VARCHAR(64),
  is_tab BOOLEAN DEFAULT FALSE,
  tab_name VARCHAR(255),
  offline_event_id VARCHAR(128) DEFAULT NULL,
  sync_source VARCHAR(24) DEFAULT 'online',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_sales_tenant_offline_event (tenant_id, offline_event_id),
  KEY idx_sales_tenant_sync_source (tenant_id, sync_source, created_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sale_items (
  id VARCHAR(64) PRIMARY KEY,
  sale_id VARCHAR(64) NOT NULL,
  product_id VARCHAR(64),
  product_name VARCHAR(255) NOT NULL,
  price DECIMAL(12,2) DEFAULT 0,
  quantity INT DEFAULT 1,
  status ENUM('pending','accepted','ready','delivered') DEFAULT 'pending',
  workstation_id VARCHAR(64),
  ordered_at DATETIME,
  accepted_at DATETIME,
  ready_at DATETIME,
  delivered_at DATETIME,
  action_staff_id VARCHAR(64),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS delivery_orders (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  provider ENUM('uber_eats','mr_d') NOT NULL,
  external_order_id VARCHAR(128) NOT NULL,
  status ENUM('new','accepted','preparing','ready','dispatched','completed','cancelled') NOT NULL DEFAULT 'new',
  customer_name VARCHAR(255),
  customer_phone VARCHAR(64),
  delivery_address TEXT,
  subtotal DECIMAL(12,2) DEFAULT 0,
  delivery_fee DECIMAL(12,2) DEFAULT 0,
  tip_amount DECIMAL(12,2) DEFAULT 0,
  discount_amount DECIMAL(12,2) DEFAULT 0,
  total DECIMAL(12,2) DEFAULT 0,
  currency VARCHAR(8) DEFAULT 'ZAR',
  placed_at DATETIME,
  accepted_at DATETIME,
  due_at DATETIME,
  sale_id VARCHAR(64),
  raw_payload JSON DEFAULT JSON_OBJECT(),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_delivery_orders_external (tenant_id, provider, external_order_id),
  INDEX idx_delivery_orders_status (tenant_id, status, placed_at),
  INDEX idx_delivery_orders_provider (tenant_id, provider, placed_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS delivery_order_items (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  delivery_order_id VARCHAR(64) NOT NULL,
  external_item_id VARCHAR(128),
  product_id VARCHAR(64),
  product_name VARCHAR(255) NOT NULL,
  quantity DECIMAL(12,3) DEFAULT 1,
  price DECIMAL(12,2) DEFAULT 0,
  note TEXT,
  modifiers JSON DEFAULT JSON_ARRAY(),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_delivery_order_items_order (tenant_id, delivery_order_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (delivery_order_id) REFERENCES delivery_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS integration_api_keys (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(160) NOT NULL,
  key_hash CHAR(64) NOT NULL,
  key_prefix VARCHAR(32) NOT NULL,
  scopes JSON DEFAULT JSON_ARRAY(),
  status ENUM('active','revoked') NOT NULL DEFAULT 'active',
  last_used_at DATETIME,
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  revoked_at DATETIME,
  revoked_by VARCHAR(64),
  revoked_by_name VARCHAR(255),
  UNIQUE KEY uniq_integration_api_keys_hash (key_hash),
  INDEX idx_integration_api_keys_tenant (tenant_id, status, created_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS integration_webhook_events (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  api_key_id VARCHAR(64),
  source VARCHAR(80) NOT NULL,
  event_type VARCHAR(80) NOT NULL,
  idempotency_key VARCHAR(160) NOT NULL,
  status ENUM('received','applied','failed','duplicate') NOT NULL DEFAULT 'received',
  entity_type VARCHAR(80),
  entity_id VARCHAR(64),
  payload JSON DEFAULT JSON_OBJECT(),
  result JSON DEFAULT JSON_OBJECT(),
  error_message TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  processed_at DATETIME,
  UNIQUE KEY uniq_integration_webhook_events_idempotency (tenant_id, source, idempotency_key),
  INDEX idx_integration_webhook_events_tenant (tenant_id, created_at),
  INDEX idx_integration_webhook_events_status (tenant_id, status, created_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (api_key_id) REFERENCES integration_api_keys(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS promotions (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(160) NOT NULL,
  description TEXT,
  status ENUM('active','inactive') DEFAULT 'active',
  discount_type ENUM('percent','fixed') DEFAULT 'percent',
  discount_value DECIMAL(12,2) NOT NULL DEFAULT 0,
  starts_at DATETIME,
  ends_at DATETIME,
  min_subtotal DECIMAL(12,2) DEFAULT 0,
  max_discount_amount DECIMAL(12,2),
  applies_to ENUM('cart','products','categories') DEFAULT 'cart',
  target_product_ids JSON DEFAULT JSON_ARRAY(),
  target_categories JSON DEFAULT JSON_ARRAY(),
  customer_scope ENUM('all','selected','no_customer') DEFAULT 'all',
  target_customer_ids JSON DEFAULT JSON_ARRAY(),
  total_redemption_limit INT,
  per_customer_limit INT,
  redemption_count INT DEFAULT 0,
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_promotions_tenant_code (tenant_id, code),
  KEY idx_promotions_status_window (tenant_id, status, starts_at, ends_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS promotion_redemptions (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  promotion_id VARCHAR(64) NOT NULL,
  promotion_code VARCHAR(64) NOT NULL,
  sale_id VARCHAR(64) NOT NULL,
  customer_id VARCHAR(64),
  staff_id VARCHAR(64),
  discount_amount DECIMAL(12,2) DEFAULT 0,
  subtotal DECIMAL(12,2) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY idx_promotion_redemptions_promotion (tenant_id, promotion_id, created_at),
  KEY idx_promotion_redemptions_customer (tenant_id, promotion_id, customer_id),
  KEY idx_promotion_redemptions_sale (tenant_id, sale_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE,
  FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tax_periods (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  period_start DATETIME NOT NULL,
  period_end DATETIME NOT NULL,
  status ENUM('locked') DEFAULT 'locked',
  locked_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  locked_by VARCHAR(64),
  locked_by_name VARCHAR(255),
  lock_note TEXT,
  currency VARCHAR(8) DEFAULT 'ZAR',
  standard_rate DECIMAL(5,2) DEFAULT 15,
  gross_sales DECIMAL(12,2) DEFAULT 0,
  taxable_sales DECIMAL(12,2) DEFAULT 0,
  zero_rated_sales DECIMAL(12,2) DEFAULT 0,
  exempt_sales DECIMAL(12,2) DEFAULT 0,
  output_tax DECIMAL(12,2) DEFAULT 0,
  input_tax DECIMAL(12,2) DEFAULT 0,
  net_vat_payable DECIMAL(12,2) DEFAULT 0,
  invoice_count INT DEFAULT 0,
  refund_count INT DEFAULT 0,
  summary_snapshot LONGTEXT,
  report_snapshot LONGTEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_tax_periods_tenant_range (tenant_id, period_start, period_end),
  KEY idx_tax_periods_range (tenant_id, period_start, period_end),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sale_payments (
  id VARCHAR(64) PRIMARY KEY,
  sale_id VARCHAR(64) NOT NULL,
  method ENUM('cash','payfast','card','wallet','account','qr','bnpl') NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  tendered_amount DECIMAL(12,2) DEFAULT 0,
  change_amount DECIMAL(12,2) DEFAULT 0,
  tip_amount DECIMAL(12,2) DEFAULT 0,
  cash_out_amount DECIMAL(12,2) DEFAULT 0,
  provider VARCHAR(64),
  provider_device_id VARCHAR(128),
  provider_reference VARCHAR(255),
  authorization_code VARCHAR(128),
  provider_status VARCHAR(32) DEFAULT 'confirmed',
  provider_note TEXT,
  qr_payload TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS layby_orders (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  customer_id VARCHAR(64) NOT NULL,
  customer_name VARCHAR(255) NOT NULL,
  staff_id VARCHAR(64),
  staff_name VARCHAR(255),
  status ENUM('active','completed','cancelled') DEFAULT 'active',
  subtotal DECIMAL(12,2) DEFAULT 0,
  tax_amount DECIMAL(12,2) DEFAULT 0,
  tax_rate DECIMAL(5,2) DEFAULT 0,
  tax_inclusive BOOLEAN DEFAULT TRUE,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  deposit_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0,
  balance_due DECIMAL(12,2) NOT NULL DEFAULT 0,
  refund_amount DECIMAL(12,2) DEFAULT 0,
  forfeited_amount DECIMAL(12,2) DEFAULT 0,
  due_date DATE NOT NULL,
  cancel_reason TEXT,
  cancelled_by VARCHAR(64),
  cancelled_by_name VARCHAR(255),
  cancelled_at DATETIME,
  completed_sale_id VARCHAR(64),
  completed_by VARCHAR(64),
  completed_by_name VARCHAR(255),
  completed_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_layby_orders_tenant_status (tenant_id, status, due_date),
  INDEX idx_layby_orders_customer (tenant_id, customer_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
  FOREIGN KEY (completed_sale_id) REFERENCES sales(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS layby_items (
  id VARCHAR(64) PRIMARY KEY,
  layby_order_id VARCHAR(64) NOT NULL,
  product_id VARCHAR(64),
  product_name VARCHAR(255) NOT NULL,
  price DECIMAL(12,2) DEFAULT 0,
  quantity DECIMAL(12,3) NOT NULL DEFAULT 1,
  reserved_quantity DECIMAL(12,3) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_layby_items_order (layby_order_id),
  INDEX idx_layby_items_product (product_id),
  FOREIGN KEY (layby_order_id) REFERENCES layby_orders(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS layby_payments (
  id VARCHAR(64) PRIMARY KEY,
  layby_order_id VARCHAR(64) NOT NULL,
  method ENUM('cash','payfast','card','wallet','account') NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  tendered_amount DECIMAL(12,2) DEFAULT 0,
  change_amount DECIMAL(12,2) DEFAULT 0,
  staff_id VARCHAR(64),
  staff_name VARCHAR(255),
  cash_session_id VARCHAR(64),
  note TEXT,
  location_id VARCHAR(64),
  from_location_id VARCHAR(64),
  to_location_id VARCHAR(64),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_layby_payments_order (layby_order_id, created_at),
  FOREIGN KEY (layby_order_id) REFERENCES layby_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cash_sessions (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  staff_id VARCHAR(64) NOT NULL,
  staff_name VARCHAR(255),
  opened_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  closed_at DATETIME,
  submitted_at DATETIME,
  reviewed_at DATETIME,
  reviewed_by VARCHAR(64),
  reconciled_at DATETIME,
  reconciled_by VARCHAR(64),
  opening_float DECIMAL(12,2) DEFAULT 0,
  opening_breakdown JSON DEFAULT JSON_OBJECT(),
  expected_cash DECIMAL(12,2) DEFAULT 0,
  actual_cash DECIMAL(12,2) DEFAULT 0,
  closing_breakdown JSON DEFAULT JSON_OBJECT(),
  difference DECIMAL(12,2) DEFAULT 0,
  accumulated_tips DECIMAL(12,2) DEFAULT 0,
  net_tips DECIMAL(12,2) DEFAULT 0,
  status ENUM('open','closed') DEFAULT 'open',
  review_status ENUM('in_progress','submitted','reviewed','reconciled','disputed') DEFAULT 'in_progress',
  notes TEXT,
  manager_notes TEXT,
  variance_reason TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cash_movements (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  cash_session_id VARCHAR(64) NOT NULL,
  type ENUM('opening_float','cash_sale','refund','cash_drop','cash_added','cash_removed','cash_out','tip','manager_adjustment','no_sale','wallet_cash_in','wallet_cash_out') NOT NULL,
  direction ENUM('in','out','neutral') NOT NULL DEFAULT 'neutral',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  sale_id VARCHAR(64),
  payment_id VARCHAR(64),
  staff_id VARCHAR(64),
  staff_name VARCHAR(255),
  created_by VARCHAR(64),
  note TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (cash_session_id) REFERENCES cash_sessions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS manager_cash_movements (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  movement_type ENUM('safe_drop','cash_added','petty_cash','payout','wallet_cash_in','wallet_cash_out','register_close','manager_adjustment','transfer') NOT NULL,
  direction ENUM('in','out','neutral') NOT NULL DEFAULT 'neutral',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  cash_session_id VARCHAR(64),
  staff_id VARCHAR(64),
  staff_name VARCHAR(255),
  customer_id VARCHAR(64),
  customer_name VARCHAR(255),
  source_type VARCHAR(64) DEFAULT 'manager_float',
  cash_source VARCHAR(64) DEFAULT 'manager_float',
  reference_id VARCHAR(128),
  category VARCHAR(96),
  note TEXT,
  receipt_attachment_url TEXT,
  receipt_attachment_name VARCHAR(255),
  counted_breakdown JSON DEFAULT JSON_OBJECT(),
  approved_by VARCHAR(64),
  approved_by_name VARCHAR(255),
  approved_at DATETIME,
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_manager_cash_tenant_created (tenant_id, created_at),
  INDEX idx_manager_cash_reference (tenant_id, movement_type, reference_id),
  INDEX idx_manager_cash_source (tenant_id, cash_source, created_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (cash_session_id) REFERENCES cash_sessions(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS cash_custody_transfers (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  status ENUM('pending_confirmation','confirmed','cancelled') NOT NULL DEFAULT 'pending_confirmation',
  from_type ENUM('register','staff','manager_float','safe','petty_cash') NOT NULL,
  from_id VARCHAR(64),
  from_name VARCHAR(255),
  to_type ENUM('register','staff','manager_float','safe','petty_cash') NOT NULL,
  to_id VARCHAR(64),
  to_name VARCHAR(255),
  cash_session_id VARCHAR(64),
  expected_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  counted_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  variance DECIMAL(12,2) NOT NULL DEFAULT 0,
  counted_breakdown JSON DEFAULT JSON_OBJECT(),
  note TEXT,
  requested_by VARCHAR(64),
  requested_by_name VARCHAR(255),
  confirmed_by VARCHAR(64),
  confirmed_by_name VARCHAR(255),
  cancelled_by VARCHAR(64),
  cancelled_by_name VARCHAR(255),
  cancel_reason TEXT,
  requested_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  confirmed_at DATETIME,
  cancelled_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_cash_custody_tenant_status (tenant_id, status, created_at),
  INDEX idx_cash_custody_session (tenant_id, cash_session_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (cash_session_id) REFERENCES cash_sessions(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS cash_close_checkpoints (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  business_date DATE NOT NULL,
  status ENUM('balanced','review_needed') NOT NULL DEFAULT 'review_needed',
  expected_physical_cash DECIMAL(12,2) NOT NULL DEFAULT 0,
  counted_physical_cash DECIMAL(12,2) NOT NULL DEFAULT 0,
  variance DECIMAL(12,2) NOT NULL DEFAULT 0,
  manager_float DECIMAL(12,2) NOT NULL DEFAULT 0,
  open_register_cash DECIMAL(12,2) NOT NULL DEFAULT 0,
  pending_cash_up_cash DECIMAL(12,2) NOT NULL DEFAULT 0,
  wallet_liability DECIMAL(12,2) NOT NULL DEFAULT 0,
  pending_payouts DECIMAL(12,2) NOT NULL DEFAULT 0,
  petty_cash_today DECIMAL(12,2) NOT NULL DEFAULT 0,
  wallet_cash_in_today DECIMAL(12,2) NOT NULL DEFAULT 0,
  wallet_cash_out_today DECIMAL(12,2) NOT NULL DEFAULT 0,
  custody_pending_count INT NOT NULL DEFAULT 0,
  custody_variance_today DECIMAL(12,2) NOT NULL DEFAULT 0,
  unresolved_items JSON DEFAULT JSON_ARRAY(),
  counted_breakdown JSON DEFAULT JSON_OBJECT(),
  note TEXT,
  closed_by VARCHAR(64),
  closed_by_name VARCHAR(255),
  closed_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_cash_close_business_date (tenant_id, business_date),
  INDEX idx_cash_close_tenant_status (tenant_id, status, business_date),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_events (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  action VARCHAR(96) NOT NULL,
  entity_type VARCHAR(64) NOT NULL,
  entity_id VARCHAR(64),
  related_sale_id VARCHAR(64),
  staff_id VARCHAR(64),
  staff_name VARCHAR(255),
  customer_id VARCHAR(64),
  source VARCHAR(32) DEFAULT 'server',
  request_id VARCHAR(64),
  details JSON DEFAULT JSON_OBJECT(),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_audit_events_tenant_created (tenant_id, created_at),
  INDEX idx_audit_events_entity (tenant_id, entity_type, entity_id),
  INDEX idx_audit_events_staff (tenant_id, staff_id),
  INDEX idx_audit_events_request (tenant_id, request_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

-- Idempotent column + index adds for existing deployments.
ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS request_id VARCHAR(64);
ALTER TABLE audit_events ADD INDEX IF NOT EXISTS idx_audit_events_request (tenant_id, request_id);

CREATE TABLE IF NOT EXISTS stock_movements (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  item_type ENUM('product','bulk') NOT NULL DEFAULT 'product',
  product_id VARCHAR(64),
  bulk_item_id VARCHAR(64),
  item_name VARCHAR(255),
  quantity_delta DECIMAL(12,3) NOT NULL DEFAULT 0,
  previous_quantity DECIMAL(12,3) NOT NULL DEFAULT 0,
  new_quantity DECIMAL(12,3) NOT NULL DEFAULT 0,
  reason VARCHAR(64) NOT NULL,
  reason_code ENUM('receiving','sale','refund','void','adjustment','count_correction','transfer','wastage','shrinkage') NOT NULL DEFAULT 'adjustment',
  reference_type VARCHAR(64),
  reference_id VARCHAR(64),
  sale_id VARCHAR(64),
  sale_item_id VARCHAR(64),
  staff_id VARCHAR(64),
  staff_name VARCHAR(255),
  note TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_stock_movements_tenant_created (tenant_id, created_at),
  INDEX idx_stock_movements_product (tenant_id, product_id),
  INDEX idx_stock_movements_sale (tenant_id, sale_id),
  INDEX idx_stock_movements_reason_code (tenant_id, reason_code, created_at),
  INDEX idx_stock_movements_location (tenant_id, location_id, created_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS manager_tasks (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  task_type ENUM('cash_variance','sale_exception','refund_request','void_request','stock_adjustment_request','low_stock','ai_recommendation','stock_variance','offline_sync') NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT,
  priority ENUM('low','normal','high','critical') DEFAULT 'normal',
  status ENUM('open','in_review','approved','declined','done','dismissed') DEFAULT 'open',
  source_type VARCHAR(64),
  source_id VARCHAR(64),
  related_sale_id VARCHAR(64),
  related_product_id VARCHAR(64),
  assigned_to VARCHAR(64),
  requested_by VARCHAR(64),
  decided_by VARCHAR(64),
  decision_note TEXT,
  details JSON DEFAULT JSON_OBJECT(),
  due_at DATETIME,
  resolved_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_manager_task_source (tenant_id, task_type, source_type, source_id),
  INDEX idx_manager_tasks_tenant_status (tenant_id, status, updated_at),
  INDEX idx_manager_tasks_source (tenant_id, source_type, source_id),
  INDEX idx_manager_tasks_assigned (tenant_id, assigned_to),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS manager_overrides (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  override_type VARCHAR(64) NOT NULL DEFAULT 'manager_task',
  target_type VARCHAR(64) NOT NULL,
  target_id VARCHAR(128) NOT NULL,
  action VARCHAR(64) NOT NULL,
  status VARCHAR(64),
  reason TEXT NOT NULL,
  requested_by VARCHAR(64),
  approved_by VARCHAR(64),
  approved_by_name VARCHAR(255),
  related_sale_id VARCHAR(64),
  related_product_id VARCHAR(64),
  source VARCHAR(64) DEFAULT 'manager_action_center',
  details JSON DEFAULT JSON_OBJECT(),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_manager_overrides_tenant_created (tenant_id, created_at),
  INDEX idx_manager_overrides_target (tenant_id, target_type, target_id),
  INDEX idx_manager_overrides_approved_by (tenant_id, approved_by, created_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_take_sessions (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  type ENUM('full','cycle','spot_check') NOT NULL DEFAULT 'cycle',
  status ENUM('draft','active','submitted','approved','cancelled') NOT NULL DEFAULT 'active',
  assigned_by VARCHAR(64),
  assigned_by_name VARCHAR(255),
  due_at DATETIME,
  notes TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  submitted_at DATETIME,
  approved_at DATETIME,
  approved_by VARCHAR(64),
  approved_by_name VARCHAR(255),
  INDEX idx_stock_take_sessions_tenant_status (tenant_id, status, updated_at),
  INDEX idx_stock_take_sessions_type_due (tenant_id, type, due_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_take_items (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  session_id VARCHAR(64) NOT NULL,
  product_id VARCHAR(64) NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  barcode VARCHAR(128),
  expected_quantity DECIMAL(12,3) NOT NULL DEFAULT 0,
  counted_quantity DECIMAL(12,3),
  variance_quantity DECIMAL(12,3),
  assigned_to VARCHAR(64),
  assigned_to_name VARCHAR(255),
  counted_by VARCHAR(64),
  counted_by_name VARCHAR(255),
  variance_reason VARCHAR(64),
  variance_reason_label VARCHAR(128),
  variance_severity ENUM('none','low','medium','high','critical') NOT NULL DEFAULT 'none',
  supervisor_recount_required TINYINT(1) NOT NULL DEFAULT 0,
  supervisor_recount_threshold DECIMAL(12,3) NOT NULL DEFAULT 0,
  supervisor_recount_at DATETIME,
  supervisor_recount_by VARCHAR(64),
  supervisor_recount_by_name VARCHAR(255),
  status ENUM('assigned','counted','confirmed','recount') NOT NULL DEFAULT 'assigned',
  counted_at DATETIME,
  confirmed_at DATETIME,
  confirmed_by VARCHAR(64),
  confirmed_by_name VARCHAR(255),
  note TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_stock_take_item_product (session_id, product_id),
  INDEX idx_stock_take_items_tenant_status (tenant_id, status, updated_at),
  INDEX idx_stock_take_items_assigned (tenant_id, assigned_to, status),
  INDEX idx_stock_take_items_product (tenant_id, product_id),
  INDEX idx_stock_take_items_supervisor_recount (tenant_id, supervisor_recount_required, status),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (session_id) REFERENCES stock_take_sessions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_take_rules (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  status ENUM('active','paused') NOT NULL DEFAULT 'active',
  schedule_type ENUM('daily') NOT NULL DEFAULT 'daily',
  run_time VARCHAR(5) NOT NULL DEFAULT '08:00',
  product_scope ENUM('random','low_stock','category','manual') NOT NULL DEFAULT 'random',
  product_count INT NOT NULL DEFAULT 5,
  category VARCHAR(255),
  product_ids JSON DEFAULT JSON_ARRAY(),
  assigned_to VARCHAR(64),
  assigned_to_name VARCHAR(255),
  last_run_for_date DATE,
  last_run_at DATETIME,
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_stock_take_rules_tenant_status (tenant_id, status, run_time),
  INDEX idx_stock_take_rules_assigned (tenant_id, assigned_to),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS customer_payout_requests (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  customer_id VARCHAR(64),
  customer_name VARCHAR(255),
  customer_email VARCHAR(255),
  amount DECIMAL(12,2) DEFAULT 0,
  status ENUM('pending','approved','rejected','paid') DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  processed_at DATETIME,
  processed_by VARCHAR(128),
  note TEXT,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  channel VARCHAR(255) NOT NULL,
  sender_id VARCHAR(128) NOT NULL,
  sender_name VARCHAR(255) NOT NULL,
  sender_role VARCHAR(255) NOT NULL,
  text TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  read_by JSON DEFAULT JSON_ARRAY(),
  is_dev_broadcast BOOLEAN DEFAULT FALSE,
  is_system BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS push_notification_settings (
  tenant_id VARCHAR(64) PRIMARY KEY,
  vapid_public_key TEXT,
  vapid_private_key TEXT,
  subject VARCHAR(255) NOT NULL DEFAULT 'mailto:dev@masepos.local',
  enabled BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  staff_id VARCHAR(64),
  endpoint VARCHAR(500) NOT NULL,
  p256dh VARCHAR(255) NOT NULL,
  auth VARCHAR(255) NOT NULL,
  expiration_time TIMESTAMP NULL,
  device_label VARCHAR(160),
  user_agent VARCHAR(500),
  disabled_at TIMESTAMP NULL,
  last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_push_subscription_endpoint (tenant_id, endpoint),
  INDEX idx_push_subscriptions_tenant (tenant_id),
  INDEX idx_push_subscriptions_staff (tenant_id, staff_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  vendor_id VARCHAR(64),
  status ENUM('draft','sent','received','cancelled') DEFAULT 'draft',
  type ENUM('once_off','recurring') DEFAULT 'once_off',
  recurring_frequency ENUM('weekly','monthly'),
  items JSON NOT NULL,
  total_amount DECIMAL(12,2) DEFAULT 0,
  expected_delivery_date DATETIME,
  invoice_status ENUM('unpaid','paid') DEFAULT 'unpaid',
  invoice_number VARCHAR(128),
  invoice_date DATETIME,
  received_at DATETIME,
  received_by VARCHAR(64),
  received_by_name VARCHAR(255),
  receiving_note TEXT,
  received_total_amount DECIMAL(12,2) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS event_bookings (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  customer_id VARCHAR(64),
  customer_name VARCHAR(255),
  contact_phone VARCHAR(64),
  contact_email VARCHAR(255),
  title VARCHAR(255) NOT NULL,
  event_type ENUM('private','public','restaurant','catering','other') NOT NULL DEFAULT 'private',
  status ENUM('inquiry','confirmed','in_progress','completed','cancelled') NOT NULL DEFAULT 'inquiry',
  start_at DATETIME NOT NULL,
  end_at DATETIME,
  guest_count INT DEFAULT 0,
  table_numbers JSON DEFAULT JSON_ARRAY(),
  table_ids JSON DEFAULT JSON_ARRAY(),
  deposit_amount DECIMAL(12,2) DEFAULT 0,
  deposit_status ENUM('none','unpaid','paid','refunded') DEFAULT 'none',
  deposit_due_at DATETIME,
  deposit_paid_at DATETIME,
  deposit_reference VARCHAR(128),
  menu_notes TEXT,
  internal_notes TEXT,
  reminder_at DATETIME,
  reminder_status ENUM('none','pending','sent','failed','skipped') DEFAULT 'none',
  reminder_sent_at DATETIME,
  reminder_note TEXT,
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_event_bookings_calendar (tenant_id, start_at, status),
  INDEX idx_event_bookings_customer (tenant_id, customer_id),
  INDEX idx_event_bookings_deposits (tenant_id, deposit_status, deposit_due_at),
  INDEX idx_event_bookings_reminders (tenant_id, reminder_status, reminder_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_batches (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  product_id VARCHAR(64) NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  purchase_order_id VARCHAR(64),
  vendor_id VARCHAR(64),
  supplier_invoice_number VARCHAR(128),
  supplier_invoice_date DATE,
  batch_number VARCHAR(128),
  received_quantity DECIMAL(12,3) NOT NULL DEFAULT 0,
  remaining_quantity DECIMAL(12,3) NOT NULL DEFAULT 0,
  unit_cost DECIMAL(12,2) DEFAULT 0,
  expiry_date DATE,
  received_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  received_by VARCHAR(64),
  received_by_name VARCHAR(255),
  location_id VARCHAR(64),
  status ENUM('active','depleted','expired') NOT NULL DEFAULT 'active',
  note TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_stock_batches_tenant_expiry (tenant_id, status, expiry_date),
  INDEX idx_stock_batches_product (tenant_id, product_id, status, expiry_date),
  INDEX idx_stock_batches_location (tenant_id, location_id, status, expiry_date),
  INDEX idx_stock_batches_purchase_order (tenant_id, purchase_order_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_transfer_orders (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  from_location_id VARCHAR(64) NOT NULL,
  to_location_id VARCHAR(64) NOT NULL,
  status ENUM('draft','requested','approved','in_transit','completed','cancelled') NOT NULL DEFAULT 'requested',
  requested_by VARCHAR(64),
  requested_by_name VARCHAR(255),
  approved_by VARCHAR(64),
  approved_by_name VARCHAR(255),
  completed_by VARCHAR(64),
  completed_by_name VARCHAR(255),
  notes TEXT,
  completed_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_stock_transfer_orders_status (tenant_id, status, updated_at),
  INDEX idx_stock_transfer_orders_locations (tenant_id, from_location_id, to_location_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_transfer_items (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  transfer_id VARCHAR(64) NOT NULL,
  product_id VARCHAR(64) NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL DEFAULT 0,
  from_previous_quantity DECIMAL(12,3) DEFAULT 0,
  from_new_quantity DECIMAL(12,3) DEFAULT 0,
  to_previous_quantity DECIMAL(12,3) DEFAULT 0,
  to_new_quantity DECIMAL(12,3) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_stock_transfer_items_transfer (tenant_id, transfer_id),
  INDEX idx_stock_transfer_items_product (tenant_id, product_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reorder_recommendations (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  product_id VARCHAR(64) NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  status ENUM('open','in_review','approved','ordered','dismissed') NOT NULL DEFAULT 'open',
  priority ENUM('low','normal','high','critical') NOT NULL DEFAULT 'high',
  current_stock DECIMAL(12,3) NOT NULL DEFAULT 0,
  min_stock DECIMAL(12,3) NOT NULL DEFAULT 0,
  target_stock DECIMAL(12,3) NOT NULL DEFAULT 0,
  recommended_quantity DECIMAL(12,3) NOT NULL DEFAULT 0,
  estimated_unit_cost DECIMAL(12,2) DEFAULT 0,
  estimated_total_cost DECIMAL(12,2) DEFAULT 0,
  avg_daily_sales DECIMAL(12,3) DEFAULT 0,
  days_of_cover INT DEFAULT 14,
  vendor_id VARCHAR(64),
  location_id VARCHAR(64),
  source VARCHAR(32) DEFAULT 'min_stock',
  evidence JSON DEFAULT JSON_ARRAY(),
  purchase_order_id VARCHAR(64),
  requested_by VARCHAR(64),
  requested_by_name VARCHAR(255),
  approved_by VARCHAR(64),
  approved_by_name VARCHAR(255),
  approved_at DATETIME,
  dismissed_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_reorder_recommendations_status (tenant_id, status, priority, updated_at),
  INDEX idx_reorder_recommendations_product (tenant_id, product_id, status),
  INDEX idx_reorder_recommendations_purchase_order (tenant_id, purchase_order_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reorder_notification_rules (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  status ENUM('active','inactive') NOT NULL DEFAULT 'active',
  location_id VARCHAR(64),
  trigger_type ENUM('below_threshold','critical_only','days_cover') NOT NULL DEFAULT 'below_threshold',
  priority ENUM('normal','high','critical') NOT NULL DEFAULT 'high',
  days_of_cover INT DEFAULT 14,
  vendor_id VARCHAR(64),
  notify_roles JSON DEFAULT JSON_ARRAY(),
  last_run_at DATETIME,
  last_result JSON DEFAULT JSON_OBJECT(),
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_reorder_notification_rules_status (tenant_id, status, location_id),
  INDEX idx_reorder_notification_rules_location (tenant_id, location_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vendors (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  contact_person VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(64),
  address TEXT,
  status ENUM('active','inactive') DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payout_requests (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  staff_id VARCHAR(64),
  staff_name VARCHAR(255),
  customer_id VARCHAR(64),
  customer_name VARCHAR(255),
  customer_email VARCHAR(255),
  amount DECIMAL(12,2) DEFAULT 0,
  status ENUM('pending','approved','rejected','paid') DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  processed_at DATETIME,
  processed_by VARCHAR(128),
  note TEXT,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS table_sections (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  color VARCHAR(64),
  `order` INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS restaurant_tables (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  label VARCHAR(255) NOT NULL,
  section_id VARCHAR(64),
  capacity INT DEFAULT 1,
  status ENUM('active','inactive') DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_settings (
  tenant_id VARCHAR(64) PRIMARY KEY,
  enabled BOOLEAN DEFAULT TRUE,
  provider VARCHAR(32) DEFAULT 'openai',
  model VARCHAR(64) DEFAULT 'gpt-5-mini',
  api_key TEXT,
  base_url VARCHAR(255),
  workspace_slug VARCHAR(128),
  insights_enabled BOOLEAN DEFAULT TRUE,
  staff_scoring_enabled BOOLEAN DEFAULT TRUE,
  visible_roles JSON DEFAULT JSON_ARRAY('admin', 'manager', 'dev'),
  staff_score_visible_roles JSON DEFAULT JSON_ARRAY('admin', 'manager', 'dev'),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_insights (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  category ENUM('sales','stock','cash','staff','restaurant','customer','package') NOT NULL,
  severity ENUM('info','success','warning','critical') NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NOT NULL,
  recommendation TEXT NOT NULL,
  evidence JSON DEFAULT JSON_ARRAY(),
  confidence INT DEFAULT 0,
  status ENUM('open','dismissed','done') DEFAULT 'open',
  source ENUM('deterministic','openai') DEFAULT 'deterministic',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_staff_scores (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  staff_id VARCHAR(64) NOT NULL,
  staff_name VARCHAR(255) NOT NULL,
  period_start DATETIME NOT NULL,
  period_end DATETIME NOT NULL,
  score INT NOT NULL DEFAULT 0,
  grade VARCHAR(32) NOT NULL,
  component_scores JSON DEFAULT JSON_OBJECT(),
  strengths JSON DEFAULT JSON_ARRAY(),
  coaching_notes JSON DEFAULT JSON_ARRAY(),
  badges JSON DEFAULT JSON_ARRAY(),
  risk_flags JSON DEFAULT JSON_ARRAY(),
  source ENUM('deterministic','openai') DEFAULT 'deterministic',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_audit_log (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  action VARCHAR(64) NOT NULL,
  requested_by VARCHAR(64),
  provider VARCHAR(32),
  status VARCHAR(32) NOT NULL,
  details JSON DEFAULT JSON_OBJECT(),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_agent_runs (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  mode ENUM('invoice','low_stock','event') NOT NULL,
  status ENUM('draft','applying','completed','failed') NOT NULL DEFAULT 'draft',
  summary TEXT NOT NULL,
  requires_human_approval BOOLEAN DEFAULT TRUE,
  full_autopilot BOOLEAN DEFAULT FALSE,
  requested_by VARCHAR(64),
  requested_by_name VARCHAR(255),
  warnings JSON DEFAULT JSON_ARRAY(),
  data_access JSON DEFAULT JSON_ARRAY(),
  apply_result JSON DEFAULT JSON_OBJECT(),
  applied_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ai_agent_runs_tenant_created (tenant_id, created_at),
  INDEX idx_ai_agent_runs_tenant_status (tenant_id, status, created_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_agent_run_steps (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  run_id VARCHAR(64) NOT NULL,
  step_id VARCHAR(64) NOT NULL,
  step_type VARCHAR(64) NOT NULL,
  label TEXT NOT NULL,
  risk ENUM('low','medium','high') NOT NULL,
  confidence DECIMAL(5,4) DEFAULT 0,
  approved BOOLEAN DEFAULT FALSE,
  status ENUM('pending','approved','applied','skipped','failed') NOT NULL DEFAULT 'pending',
  payload JSON DEFAULT JSON_OBJECT(),
  evidence JSON DEFAULT JSON_ARRAY(),
  result JSON DEFAULT JSON_OBJECT(),
  skip_reason TEXT,
  approved_by VARCHAR(64),
  approved_by_name VARCHAR(255),
  approved_at DATETIME,
  applied_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_ai_agent_step_run_step (tenant_id, run_id, step_id),
  INDEX idx_ai_agent_steps_run (tenant_id, run_id, status),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (run_id) REFERENCES ai_agent_runs(id) ON DELETE CASCADE
);

INSERT INTO tenants (id, name) VALUES ('default', 'Default Tenant');

INSERT INTO staff (id, tenant_id, name, role, email, password_hash, status)
VALUES (
  'admin',
  'default',
  'Admin',
  'dev',
  'jameskoen78@gmail.com',
  '$2b$10$cllz1VjHJl97oeAyzvZWsOpYd66l7kaOXG977GZ6yDT6C58SgMf9S',
  'active'
);

CREATE TABLE IF NOT EXISTS bulk_items (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  item_type ENUM('single','bulk') DEFAULT 'single',
  unit VARCHAR(32) NOT NULL DEFAULT 'items', -- ml, g, kg, items, etc.
  stock DECIMAL(12,3) DEFAULT 0,
  min_stock DECIMAL(12,3) DEFAULT 0,
  cost_per_unit DECIMAL(12,2) DEFAULT 0,
  barcode VARCHAR(255),
  pack_name VARCHAR(64),
  pack_quantity DECIMAL(12,3) DEFAULT 1,
  single_unit_name VARCHAR(64) DEFAULT 'item',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product_recipes (
  product_id VARCHAR(64) NOT NULL,
  bulk_item_id VARCHAR(64) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL, -- e.g. 25.000 for ml
  yield_quantity DECIMAL(12,3) DEFAULT 1,
  waste_percent DECIMAL(5,2) DEFAULT 0,
  substitute_group VARCHAR(64),
  substitute_rank INT DEFAULT 0,
  is_optional BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (product_id, bulk_item_id),
  INDEX idx_product_recipes_substitute_group (product_id, substitute_group, substitute_rank),
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  FOREIGN KEY (bulk_item_id) REFERENCES bulk_items(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product_modifiers (
  id VARCHAR(64) PRIMARY KEY,
  product_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  type ENUM('single', 'multiple') DEFAULT 'single',
  required BOOLEAN DEFAULT FALSE,
  min_selection INT DEFAULT 0,
  max_selection INT DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS modifier_options (
  id VARCHAR(64) PRIMARY KEY,
  modifier_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  price_extra DECIMAL(12,2) DEFAULT 0,
  bulk_item_id VARCHAR(64), -- Optional: modifier can also deduct from bulk stock
  bulk_quantity DECIMAL(12,3) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (modifier_id) REFERENCES product_modifiers(id) ON DELETE CASCADE,
  FOREIGN KEY (bulk_item_id) REFERENCES bulk_items(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS realtime_pubsub_events (
  id VARCHAR(64) PRIMARY KEY,
  instance_id VARCHAR(128) NOT NULL,
  channel VARCHAR(255) NOT NULL,
  event_name VARCHAR(128) NOT NULL,
  payload LONGTEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME,
  INDEX idx_realtime_pubsub_poll (created_at, id),
  INDEX idx_realtime_pubsub_expiry (expires_at)
);
